### ISSUE TITLE
Should throw exception if application does not have IAM permissions to access aws ssm

### ISSUE THREAD

**Issue by billy-bacon** [lmeadors/jackson-env#3]
https://github.com/lmeadors/jackson-env/blob/81ce45603633c6af15aa9bdbe6d71bd62d8cfa55/src/main/java/com/elmsoftware/env/settingproviderimpl/AwsSsmSettingProvider.java#L47

If an IAM role permission issue is thrown, the exception should bubble up to the caller. I ran into this issue because the IAM role that the ElasticBeanstalk environment uses did not have ssm permissions and all that was logged is that it couldn't find /global/{variable_name} and the parameter was defined in aws ssm. Would be helpful for debugging/troubleshooting.

Same goes for v2 of this setting provider.

**Comment by lmeadors** [comment]
I will not re-throw the exception caught here, because I am not going to get into the business of parsing exceptions and deciding which are worth throwing and which are to be logged:

https://github.com/lmeadors/jackson-env/blob/81ce45603633c6af15aa9bdbe6d71bd62d8cfa55/src/main/java/com/elmsoftware/env/settingproviderimpl/AwsSsmSettingProvider.java#L47

However, I can provide a mechanism for handling those better using the `ProviderExceptionHandler` class - that will allow you to intercept that exception if you want to without breaking backward compatibility.

**Comment by lmeadors** [comment]
This is deployed and merged to master now - it will take a while to distribute to all the maven repos, but there is nothing more for me to do with it. ¯\_(ツ)_/¯
